# Generated by Django 5.1.4 on 2025-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=3)),
                ('nationality', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
