# Generated by Django 5.1.5 on 2025-01-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buts_par_match', models.FloatField()),
                ('buts_sur_penalty', models.CharField(max_length=10)),
                ('buts_du_coup_franc', models.CharField(max_length=10)),
                ('buts_dans_surface', models.CharField(max_length=10)),
                ('buts_hors_surface', models.CharField(max_length=10)),
                ('buts_pied_gauche', models.IntegerField()),
                ('buts_pied_droit', models.IntegerField()),
                ('buts_de_la_tete', models.IntegerField()),
                ('grandes_chances_par_match', models.FloatField()),
                ('grosses_occasions_manquees', models.FloatField()),
                ('total_tirs_par_match', models.FloatField()),
                ('tirs_cadres_par_match', models.FloatField()),
                ('tirs_non_cadres_par_match', models.FloatField()),
                ('tirs_bloques_par_match', models.FloatField()),
                ('dribbles_reussis_par_match', models.FloatField()),
                ('corners_par_match', models.FloatField()),
                ('coups_francs_par_match', models.FloatField()),
                ('frappe_sur_poteau', models.IntegerField()),
                ('contre_attaques', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_inviolee', models.IntegerField()),
                ('buts_encaisses_par_match', models.FloatField()),
                ('tacles_par_match', models.FloatField()),
                ('interceptions_par_match', models.FloatField()),
                ('degagements_par_match', models.FloatField()),
                ('arrets_par_match', models.FloatField()),
                ('ballons_recuperes_par_match', models.FloatField()),
                ('erreurs_menant_a_un_tir', models.IntegerField()),
                ('erreurs_provoquant_un_but', models.IntegerField()),
                ('penalties_concedes', models.IntegerField()),
                ('buts_sur_penalty_concedes', models.IntegerField()),
                ('degagement_ligne_de_but', models.IntegerField()),
                ('dernier_homme_attaquer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('state', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.FloatField()),
                ('precision_par_match', models.CharField(max_length=20)),
                ('precision_son_camp', models.CharField(max_length=20)),
                ('precision_camp_adverse', models.CharField(max_length=20)),
                ('precision_longues_passes', models.CharField(max_length=20)),
                ('bons_centres', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('entraineur', models.CharField(max_length=50)),
                ('classement', models.CharField(max_length=20)),
                ('joueurs_total', models.IntegerField()),
                ('moyenne_age', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
