# Generated by Django 5.1.5 on 2025-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='goal_kicks_per_game',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
