# Generated by Django 5.1.5 on 2025-02-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalkeeperstats',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='rating',
            field=models.FloatField(),
        ),
    ]
