# Generated by Django 5.1.5 on 2025-01-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matche',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.league'),
        ),
        migrations.AddField(
            model_name='matche',
            name='teamA',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='myapp.team'),
        ),
        migrations.AddField(
            model_name='matche',
            name='teamB',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='myapp.team'),
        ),
    ]
