# Generated by Django 5.1.5 on 2025-02-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='classement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='entraineur',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='joueurs_total',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='moyenne_age',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
                ('teamID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
    ]
