# Generated by Django 5.1.5 on 2025-03-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_other_goal_kicks_per_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opponent',
            name='passes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passing'),
        ),
    ]
