# Generated by Django 5.1.5 on 2025-01-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_matche_league_matche_teama_matche_teamb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attack',
        ),
        migrations.DeleteModel(
            name='Defense',
        ),
        migrations.DeleteModel(
            name='Passes',
        ),
    ]
