# Generated by Django 5.1.5 on 2025-03-10 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_is_manager_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_signup', 'Nouvel utilisateur inscrit'), ('manager_added', 'Nouveau gestionnaire ajouté'), ('players_scraped', 'Joueurs ajoutés via scraping'), ('teams_scraped', 'Équipes ajoutées via scraping'), ('leagues_scraped', 'Ligues ajoutées via scraping'), ('scraping_update', 'Mise à jour du scraping')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user')),
            ],
        ),
    ]
