# Generated by Django 5.1.5 on 2025-02-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_team_classement_alter_team_entraineur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
