# Generated by Django 5.1.5 on 2025-01-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_attack_delete_defense_delete_passes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grosses_occasions_realisees', models.PositiveIntegerField(blank=True, null=True)),
                ('grosses_occasions_manquees', models.PositiveIntegerField(blank=True, null=True)),
                ('touchers_surface_reparation', models.PositiveIntegerField(blank=True, null=True)),
                ('tacles_recus_dernier_tiers', models.PositiveIntegerField(blank=True, null=True)),
                ('hors_jeux', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacles_gagnes', models.IntegerField(blank=True, null=True)),
                ('tacles_totaux', models.IntegerField(blank=True, null=True)),
                ('interceptions', models.IntegerField(blank=True, null=True)),
                ('recuperations', models.IntegerField(blank=True, null=True)),
                ('degagements', models.IntegerField(blank=True, null=True)),
                ('erreurs_menant_a_un_but', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duels', models.IntegerField(blank=True, null=True)),
                ('pertes_balle', models.IntegerField(blank=True, null=True)),
                ('duels_sol', models.IntegerField(blank=True, null=True)),
                ('duels_aeriens', models.IntegerField(blank=True, null=True)),
                ('dribbles', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GardienDeBut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrets_du_gardien', models.IntegerField(blank=True, null=True)),
                ('sorties_aeriennes', models.IntegerField(blank=True, null=True)),
                ('coup_de_pied_de_but', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passes_precises', models.IntegerField(blank=True, null=True)),
                ('touches', models.IntegerField(blank=True, null=True)),
                ('passes_vers_dernier_tiers', models.IntegerField(blank=True, null=True)),
                ('dans_le_dernier_tiers', models.IntegerField(blank=True, null=True)),
                ('longs_ballons', models.IntegerField(blank=True, null=True)),
                ('transversales', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sommaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grandes_chances', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tirs', models.PositiveIntegerField(blank=True, null=True)),
                ('arrets_gardien', models.PositiveIntegerField(blank=True, null=True)),
                ('corner', models.PositiveIntegerField(blank=True, null=True)),
                ('fautes', models.PositiveIntegerField(blank=True, null=True)),
                ('passes', models.PositiveIntegerField(blank=True, null=True)),
                ('tacles', models.PositiveIntegerField(blank=True, null=True)),
                ('coups_francs', models.PositiveIntegerField(blank=True, null=True)),
                ('cartons_jaunes', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tirs_cadres', models.PositiveIntegerField(blank=True, null=True)),
                ('frappe_sur_poteau', models.PositiveIntegerField(blank=True, null=True)),
                ('tirs_non_cadres', models.PositiveIntegerField(blank=True, null=True)),
                ('tirs_bloques', models.PositiveIntegerField(blank=True, null=True)),
                ('tirs_dans_surface', models.PositiveIntegerField(blank=True, null=True)),
                ('tirs_hors_surface', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
