# Generated by Django 5.1.5 on 2025-02-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_attaque_defense_duel_gardiendebut_passes_sommaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GardienDeBut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gardiendebut')),
                ('attaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.attaque')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.defense')),
                ('duels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.duel')),
                ('matcheID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.matche')),
                ('passes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passes')),
                ('sommaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sommaire')),
                ('tirs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tirs')),
            ],
        ),
    ]
