# Generated by Django 5.1.5 on 2025-02-21 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='accurate_passes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='aerial_duels_won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='clearances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='crosses_accurate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='dribble_attempts_successful',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='dribbled_past',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='fouls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='ground_duels_won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='interceptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='key_passes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='long_balls_accurate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='minutes_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='shots_blocked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='shots_off_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='shots_on_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='total_passes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='total_tackles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='touches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='was_fouled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerStatsWithTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_joues', models.IntegerField(blank=True, null=True)),
                ('but', models.IntegerField(blank=True, null=True)),
                ('passes_decisive', models.IntegerField(blank=True, null=True)),
                ('touches', models.IntegerField(blank=True, null=True)),
                ('passes_precises', models.IntegerField(blank=True, null=True)),
                ('passes_cles', models.IntegerField(blank=True, null=True)),
                ('centres', models.IntegerField(blank=True, null=True)),
                ('passes_en_profondeur', models.IntegerField(blank=True, null=True)),
                ('tirs_cadres', models.IntegerField(blank=True, null=True)),
                ('tirs_non_cadres', models.IntegerField(blank=True, null=True)),
                ('tirs_bloques', models.IntegerField(blank=True, null=True)),
                ('tentatives_de_dribble', models.IntegerField(blank=True, null=True)),
                ('duels_au_sol', models.IntegerField(blank=True, null=True)),
                ('duels_aeriennes', models.IntegerField(blank=True, null=True)),
                ('perte_de_balle', models.IntegerField(blank=True, null=True)),
                ('tacles_recus', models.IntegerField(blank=True, null=True)),
                ('fautes', models.IntegerField(blank=True, null=True)),
                ('degagements', models.IntegerField(blank=True, null=True)),
                ('interceptions', models.IntegerField(blank=True, null=True)),
                ('tacles_totaux', models.IntegerField(blank=True, null=True)),
                ('dribbles_subis', models.IntegerField(blank=True, null=True)),
                ('grosses_occasions_crees', models.IntegerField(blank=True, null=True)),
                ('hors_jeux', models.IntegerField(blank=True, null=True)),
                ('sauves', models.IntegerField(blank=True, null=True)),
                ('degagements_des_poings', models.IntegerField(blank=True, null=True)),
                ('sorties', models.IntegerField(blank=True, null=True)),
                ('sorties_aeriennes', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.matche')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
            ],
        ),
    ]
