# Generated by Django 5.1.5 on 2025-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_playerstats_accurate_passes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatswithteam',
            name='but_attendus',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatswithteam',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='matche',
            name='state',
            field=models.CharField(blank=True, choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='but',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='centres',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='degagements',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='degagements_des_poings',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='dribbles_subis',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='duels_aeriennes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='duels_au_sol',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='fautes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='grosses_occasions_crees',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='hors_jeux',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='interceptions',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='minutes_joues',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='passes_cles',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='passes_decisive',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='passes_en_profondeur',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='passes_precises',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='perte_de_balle',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='sauves',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='sorties',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='sorties_aeriennes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='tacles_recus',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='tacles_totaux',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='tentatives_de_dribble',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='tirs_bloques',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='tirs_cadres',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='tirs_non_cadres',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatswithteam',
            name='touches',
            field=models.CharField(blank=True, null=True),
        ),
    ]
