# Generated by Django 5.1.5 on 2025-02-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_profilemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalkeeperStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('saves_from_inside_box', models.IntegerField()),
                ('clearances', models.IntegerField()),
                ('blocked_shots', models.IntegerField()),
                ('shots_on_target', models.IntegerField()),
                ('shots_off_target', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.matche')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.IntegerField()),
                ('shots_on_target', models.IntegerField()),
                ('shots_off_target', models.IntegerField()),
                ('shots_blocked', models.IntegerField()),
                ('dribble_attempts_successful', models.IntegerField()),
                ('touches', models.IntegerField()),
                ('accurate_passes', models.IntegerField()),
                ('total_passes', models.IntegerField()),
                ('key_passes', models.IntegerField()),
                ('crosses_accurate', models.IntegerField()),
                ('long_balls_accurate', models.IntegerField()),
                ('ground_duels_won', models.IntegerField()),
                ('aerial_duels_won', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('was_fouled', models.IntegerField()),
                ('clearances', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('total_tackles', models.IntegerField()),
                ('dribbled_past', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.matche')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
            ],
        ),
    ]
